--1)What is the total revenue generated by male vs. female customers?
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

--2)Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer
      );


--3)which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating)::numeric, 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--4)Compare the average purchase amounts between Standard and Express shipping
select shipping_type,
round(avg(purchase_amount)::numeric,2)
from customer 
where shipping_type in('standard','express')
group by shipping_type;


--5)Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
 SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend,
       ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


--6)Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)::numeric
           / COUNT(*) * 100,
           2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--7)Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of customers in each segment.
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'new'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
               ELSE 'loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS "number of customers"
FROM customer_type
GROUP BY customer_segment;

--8)What are the top 3 most purchased products within each category?


with item_counts as(
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3;

--9)Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id)as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status


--10)What is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
